# Generated by Django 5.1.5 on 2025-01-15 16:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="movieorder",
            old_name="buyed_at",
            new_name="created_at",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="user",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="users_buyers",
        ),
        migrations.RemoveField(
            model_name="movieorder",
            name="user",
        ),
        migrations.AddField(
            model_name="movie",
            name="added_by",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="added_movies",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="movieorder",
            name="ordered_by",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="movie_orders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="duration",
            field=models.CharField(default="00:00:00", max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="movie",
            name="rating",
            field=models.CharField(
                choices=[
                    ("G", "General"),
                    ("PG", "Parental Guidance"),
                    ("R", "Restricted"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="synopsis",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="title",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="movieorder",
            name="movie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="movies.movie",
            ),
        ),
        migrations.AlterField(
            model_name="movieorder",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
